SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM reels;
DELETE FROM drop_items;
DELETE FROM food_drops;
DELETE FROM order_items;
DELETE FROM payments;
DELETE FROM ratings;
DELETE FROM creator_follows;
DELETE FROM orders;
DELETE FROM menu_items;
DELETE FROM creator_verifications;
DELETE FROM restaurants;
DELETE FROM users WHERE role != 'ADMIN';
SET FOREIGN_KEY_CHECKS = 1;
